apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: tito-prod
  labels:
    app: tito
  type: Opaque
  data:
    password: Vk13YXJlMSE=
  # Password created like this: echo -n 'VMware1!' | base64
