apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: tito-prod
  labels:
    type: local
spec:
  storageClassName: default
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
